### ISSUE TITLE
- [ ] Declarar la situación del problema

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo2_jag_ppi2020#3]

**Comment by JohnFlorez25** [comment]
@Caalvarez2020 @ybedoya2020 Recuerden que en la declaración de la situación del problema solo se menciona lo que concierne al problema, no como se va a dar solución o que se va a buscar para solucionarlo, deben apoyarse mucho en el diagrama de espina de pescado para dejar claro cual es el problema y sus causas , y además finalmente puntualizar en que tiene efecto.

**Comment by Caalvarez2020** [comment]
@JohnFlorez25 Ya está listo la declaración del problema
