### ISSUE TITLE
Realizar Historias de Usuario y criterios de aceptación

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo2_jag_ppi2020#8]

**Comment by JohnFlorez25** [comment]
@Daniela0209 Deben garantizar como mínimo 10 historias de usuario con sus respectivos criterios de aceptación

**Comment by Daniela0209** [comment]
Buenas tardes profe, ya hicimos las 10 historias de usuario y el prototipo de alta fidelidad, gracias
